# Generated by Django 5.0.1 on 2024-02-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_tags', to='product.tag', verbose_name='Tags'),
        ),
    ]
